name: publish-package

on:
  release:
    types: [published]

jobs:
  ghcr:
    runs-on: ubuntu-latest
    steps:
    - name: Set meta info
      id: set-meta
      run: |
        echo ::set-output name=tag::${GITHUB_REF#refs/*/}
        echo ::set-output name=repo::$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.2.1
      with:
        install: true
    - name: Log in to GHCR
      uses: docker/login-action@v2.1.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build Image and Push to GHCR
      uses: docker/build-push-action@v3.2.0
      with:
        file: ./docker/Dockerfile
        pull: true
        push: true
        labels: |
          org.opencontainers.image.source=https://github.com/${{ github.repository }}
        tags: |
          ghcr.io/${{ steps.set-meta.outputs.repo }}:latest
          ghcr.io/${{ steps.set-meta.outputs.repo }}:${{ steps.set-meta.outputs.tag }}
